---
title: "STAT 158 Final Exam"
author: "Oliver Shanklin"
date: "May 10, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## 1)

```{r Problem 1}

n <- 30

coefs_age <- rep(0,1e4)

coefs_age2 <- rep(0,1e4)

pvalue <- numeric()
pvalue2 <- numeric()

for (i in 1:1e4) {
  
  Age <- round(runif(n,min=18,max=70))
  
  Age2 <- Age^2
  
  HR <- 94 - Age*0.5 + Age2*0.0035 + rnorm(n,sd=10)
  
  model <- lm(HR~Age+Age2)
  
  coefs_age[i] <- summary(model)$coefficients[2,1]
  
  coefs_age2[i] <- summary(model)$coefficients[3,1]
  
  pvalue[i] <- summary(model)$coefficients[2,4]
  pvalue2[i] <- summary(model)$coefficients[3,4]
  
}

```

#### a)

```{r 1a}

mean(coefs_age)

mean(coefs_age2)

```

These statistics seem correct. As age increases, we see a decline in average heart rates of $0.5$, so it is really close to our model coefficient, $-0.5$, which was stated in the $HR$ Model. The coefficient of age2 should also be really close to our model, which is true, $0.0035$.


#### b)

```{r 1b}

plot(Age, HR, main = "Age vs Heart Rate", ylab = "Heart Rate", xlab = "Age", cex = .8)


```


#### c)

```{r 1c}




```




## 2)

#### a)

```{r Problem 2}


hist(rgamma(10000, 1), breaks = 100)

hist(rgamma(10000, .5), breaks = 100)

hist(rgamma(10000, .1), breaks = 100)


```
As the shape gets smaller, the peak of the data gets closer and closer to 0.


#### b)

```{r 2b}

gamma_1 <- numeric()
gamma_2 <- numeric()


for (i in 1:1000) {
  
  gamma_1[i] <- mean(rgamma(30, 1))
  gamma_2[i] <- mean(rgamma(30, 1))
  
}

t.test(gamma_1,gamma_2)

```




## 3)

```{r Problem 3}

Ferret_Vaccine <- read.csv("C:/Users/st430/Downloads/Ferret_Vaccine.csv")
attach(Ferret_Vaccine)

```



#### a)

```{r 3a}

mean(Ferret_Vaccine$Temperature)

mean(Ferret_Vaccine$Weight)


```

#### b)

```{r 3b}

temp574 <- Temperature[Ferret.ID == "574"]
day574 <- Day[Ferret.ID == "574"]
temp546 <- Temperature[Ferret.ID == "546"]
day546 <- Day[Ferret.ID == "546"]
temp548 <- Temperature[Ferret.ID == "548"]
day548 <- Day[Ferret.ID == "548"]

plot(day574, temp574, type = "l", lty = 1,
     xlim = c(min(day574,day546,day548), max(day574, day546, day548)),
     ylim = c(min(temp574,temp546,temp548), max(temp574, temp546, temp548)),
     ylab = "Temperature", xlab = "Day")
lines(day546, temp546, type = "l", lty = 5)
lines(day548, temp548, type = "l", lty = 3)


```

#### c)

```{r 3c}

temp_vac_none <- Temperature[Vaccine =="None"]
temp_vac <- Temperature[Vaccine =="Vaccine"]

day_vac_none <- Day[Vaccine == "None"][1:16]
day_vac <- Day[Vaccine == "Vaccine"][1:16]

temp_vac_none_matrix <- matrix(temp_vac_none, ncol=16, byrow = T)
temp_vac_matrix <- matrix(temp_vac, ncol=16, byrow = T)

avg_temp_vac_none <- apply(temp_vac_none_matrix, 2, FUN = mean)
avg_temp_vac <- apply(temp_vac_matrix, 2, FUN = mean)


plot(day_vac_none, avg_temp_vac_none, type = "l", lty = 1,
     xlab = "Days", ylab = "Average Temperature")
lines(day_vac, avg_temp_vac, type = "l", lty = 5)

```


#### d)

```{r 3d}

max_temp_vac_none <- apply(temp_vac_none_matrix, 2, FUN = max)
max_temp_vac <- apply(temp_vac_matrix, 2, FUN = max)



test_vac_none <- t.test(max_temp_vac, max_temp_vac_none)



test_vac_none$statistic
test_vac_none$p.value



```
